name: GitHub Metrics

on:
  schedule: [{cron: "0 0 * * *"}]  # 每天 00:00 自动运行一次
  workflow_dispatch:              # 允许手动触发

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: ${{ github.repository_owner }}
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          plugin_languages: yes
          plugin_achievements: yes
          plugin_lines: yes
